openapi: 3.0.0
info:
  title: 'Пример реализации социальной сети'
  description: "## Соцальная сеть Шаг и компания \n\n Наша проба сделать хорошую социальную сеть"
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
    description: 'Local API server'
paths:
  /api/account/avatar-upload:
    post:
      tags:
        - account
      summary: 'Update user avatar (auth Bearer)'
      operationId: api.account.avatar.upload
      requestBody:
        description: 'upload avatar '
        required: true
        content:
          application/json:
            schema:
              properties:
                user_id:
                  type: integer
                  example: '22'
                avatar:
                  type: file
                  example: 'image content'
              type: object
      responses:
        '200':
          description: 'avatar his updated'
          content:
            application/json:
              schema:
                properties:
                  message: { type: string, example: 'Admin is updated' }
                type: object
        '422':
          description: 'not found user'
          content:
            application/json:
              schema:
                properties:
                  message: { type: string, example: 'user not found' }
                type: object
  /api/account/update-user:
    put:
      tags:
        - account
      summary: 'Update user data (auth Bearer)'
      operationId: api.account.update.user
      requestBody:
        description: 'update data is not required some'
        required: true
        content:
          application/json:
            schema:
              properties:
                user_id:
                  type: integer
                  example: '22'
                name:
                  type: string
                  example: REcountsx
                password:
                  type: password
                  example: qwerty123
              type: object
      responses:
        '200':
          description: 'Admin his updated'
          content:
            application/json:
              schema:
                properties:
                  status: { type: string, example: 'Admin his updated' }
                type: object
  /api/auth/login:
    post:
      tags:
        - auth
      summary: 'Login a user'
      operationId: api.auth.login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessLoginResource'
        '422':
          description: 'invalid password'
          content:
            application/json:
              schema:
                properties:
                  status: { type: string, example: error }
                  message: { type: string, example: Unauthorized }
                type: object
  /api/auth/logout:
    get:
      tags:
        - auth
      summary: 'Perform logout for user'
      operationId: api.auth.logout
      requestBody:
        required: false
      responses:
        '200':
          description: 'Admin successfully logged out'
          content:
            application/json:
              schema:
                properties:
                  status: { type: string, example: success }
                  message: { type: string, example: 'Admin successfully logged out' }
                type: object
        '500':
          description: 'Some internal server error occurred'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResource'
  /api/auth/register:
    post:
      tags:
        - auth
      summary: 'Register a user'
      operationId: api.auth.register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessLoginResource'
        '422':
          description: 'password confirmation'
          content:
            application/json:
              schema:
                properties:
                  status: { type: string, example: error }
                  message: { type: string, example: 'password confirmation.' }
                type: object
  /api/category:
    get:
      tags:
        - categories
      summary: 'Get all categories'
      operationId: api.category
      responses:
        '200':
          description: 'retun all categories'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponse'
  /api/post:
    post:
      tags:
        - post
      summary: 'Add post'
      operationId: api.post.store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostRequest'
      responses:
        '200':
          description: 'return new created post'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
  '/api/post/{$id}':
    get:
      tags:
        - post
      summary: 'Show post per id'
      operationId: api.post.show
      responses:
        '200':
          description: 'return post'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
    delete:
      tags:
        - post
      summary: 'Delete post per id'
      operationId: api.post.destroy
      responses:
        '200':
          description: 'return message'
          content:
            application/json:
              schema:
                properties:
                  message: { type: string, example: 'deleted post: 9' }
                type: object
  /api/post/category:
    post:
      tags:
        - post
      summary: 'Get all posts on category'
      operationId: api.post.get_on_category
      requestBody:
        description: 'get posts '
        required: true
        content:
          application/json:
            schema:
              properties:
                category_id:
                  type: integer
                  example: '22'
              type: object
      responses:
        '200':
          description: 'retun all posts on categories'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
  /api/post/user:
    post:
      tags:
        - post
      summary: 'Get all posts on author'
      operationId: api.post.get_on_user
      requestBody:
        description: 'get posts  '
        required: true
        content:
          application/json:
            schema:
              properties:
                user_id:
                  type: integer
                  example: '22'
              type: object
      responses:
        '200':
          description: 'retun all posts on author'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostResponse'
  /api/post/add_comment:
    post:
      tags:
        - operations_post
      summary: 'Add comment to post'
      operationId: api.post.add.comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
      responses:
        '200':
          description: 'comment added'
  /api/post/add_like:
    post:
      tags:
        - operations_post
      summary: 'Add like to post'
      operationId: api.post.add.like
      requestBody:
        description: 'add like '
        required: true
        content:
          application/json:
            schema:
              properties:
                post_id:
                  type: integer
                  example: '22'
              type: object
      responses:
        '200':
          description: 'added like to post'
  /api/post/add_view:
    post:
      tags:
        - operations_post
      summary: 'Add like to view'
      operationId: api.post.add.view
      requestBody:
        description: 'add like '
        required: true
        content:
          application/json:
            schema:
              properties:
                post_id:
                  type: integer
                  example: '22'
              type: object
      responses:
        '200':
          description: 'added view to post'
  /api/report/comment:
    post:
      tags:
        - report
      summary: 'report comment'
      operationId: api.report.comment
      requestBody:
        description: 'upload avatar '
        required: true
        content:
          application/json:
            schema:
              properties:
                comment_id:
                  type: integer
                  example: '22'
                who_was_reported_id:
                  type: integer
                  example: '33'
              type: object
      responses:
        '200':
          description: 'report comment'
          content:
            application/json:
              schema:
                properties: {  }
  /api/report/post:
    post:
      tags:
        - report
      summary: 'report post'
      operationId: api.report.post
      requestBody:
        description: 'upload avatar '
        required: true
        content:
          application/json:
            schema:
              properties:
                post_id:
                  type: integer
                  example: '22'
                who_was_reported_id:
                  type: integer
                  example: '33'
              type: object
      responses:
        '200':
          description: 'report post'
          content:
            application/json:
              schema:
                properties: {  }
components:
  schemas:
    ValidationError:
      properties:
        message:
          type: string
          example: 'The given data was invalid.'
        errors:
          properties:
            'key 1':
              type: array
              items:
                type: string
                example: 'Error message 1'
            'key 2':
              type: array
              items:
                type: string
                example: 'Error message 2'
          type: object
      type: object
    LoginRequest:
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: john@example.com
        password:
          type: string
          example: '123456'
      type: object
    RegisterRequest:
      required:
        - name
        - email
        - password
        - password_confirmation
      properties:
        name:
          type: string
          example: 'John Doe'
        email:
          type: string
          format: email
          example: john@example.com
        password:
          type: string
          example: '123456'
        password_confirmation:
          type: string
          example: '123456'
      type: object
    CategoryResponse:
      properties:
        id:
          type: integer
          example: '1'
        name:
          type: string
          example: News
        post_count:
          type: integer
          example: '3'
        created_at:
          type: string
          format: date-time
          example: '2024-02-06T19:22:50.000000Z'
        updated_at:
          type: string
          format: date-time
          example: '2024-02-06T19:22:50.000000Z'
      type: object
    CategoryRequest:
      properties:
        name:
          type: string
          example: News
      type: object
    CommentRequest:
      properties:
        comment_text:
          type: string
          example: 'I like codding in react'
        author_id:
          type: integer
          example: '2'
        post_id:
          type: integer
          example: '2'
      type: object
    CommentResponse:
      properties:
        id:
          type: integer
          example: '1'
        comment_text:
          type: string
          example: 'I like codding in react'
        author_id:
          type: integer
          example: '2'
        post_id:
          type: integer
          example: '2'
        created_at:
          type: string
          format: date-time
          example: '2024-02-06T19:22:50.000000Z'
        updated_at:
          type: string
          format: date-time
          example: '2024-02-06T19:22:50.000000Z'
      type: object
    PostRequest:
      properties:
        title:
          type: string
          example: 'How to create react app'
        text:
          type: string
          example: 'I like codding in react'
        author_id:
          type: integer
          example: '2'
        category_id:
          type: integer
          example: '2'
      type: object
    PostResponse:
      properties:
        title:
          type: string
          example: 'How to create react app'
        text:
          type: string
          example: 'I like codding in react'
        author_id:
          type: integer
          example: '2'
        category_id:
          type: integer
          example: '2'
        views_count:
          type: integer
          example: '2'
        likes_count:
          type: integer
          example: '2'
        created_at:
          type: string
          format: date-time
          example: '2024-02-06T19:22:50.000000Z'
        updated_at:
          type: string
          format: date-time
          example: '2024-02-06T19:22:50.000000Z'
      type: object
    SuccessLoginResource:
      properties:
        status:
          type: string
          example: 'true'
        user:
          $ref: '#/components/schemas/Admin'
        authorisation:
          $ref: '#/components/schemas/TokenResource'
      type: object
    TokenResource:
      properties:
        token:
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS9hdXRoL3JlZ2lzdGVyIiwiaWF0IjoxNzA2NTUyMTM4LCJleHAiOjE3MDY5MTIxMzgsIm5iZiI6MTcwNjU1MjEzOCwianRpIjoiRk9hclkyZ2VvckhPT1llbSIsInN1YiI6IjQiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3IiwiZW1haWwiOiJ2YXN5YTJAdmFzeWEuY29tIiwibmFtZSI6InZhc3lhMiJ9.APeVTaT7gnkVVboKkfXDndq1vjQFiiaMPCw21aS9hL8
        type:
          type: string
          example: bearer
      type: object
    InternalServerErrorResource:
      properties:
        status:
          type: string
          example: failure
        message:
          type: string
          example: 'Internal server error'
      type: object
    Admin:
      properties:
        id:
          type: integer
          example: '2'
        name:
          type: string
          example: 'John Doe'
        email:
          type: string
          format: email
          example: john@example.com
        email_verified:
          type: boolean
          example: '1'
        created_at:
          type: string
          format: date-time
          example: '2024-02-03T21:06:04.000000Z'
        updated_at:
          type: string
          format: date-time
          example: '2024-02-03T21:06:04.000000Z'
        confirmation_token:
          type: url
          example: 8ccde004-4c26-453e-a3f7-a73145dfb4a1
        avatar_url:
          type: string
          example: 'http://localhost/storage/avatars/108/original.webp'
      type: object
  securitySchemes:
    BearerToken:
      type: http
      bearerFormat: JWT
      scheme: bearer
tags:
  -
    name: auth
    description: 'Admin authentication'
  -
    name: post
    description: 'Операции с постами'
